# Generated by Django 2.2.4 on 2020-01-22 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_title', models.CharField(max_length=200, verbose_name='Названия')),
                ('articles_text', models.TextField(verbose_name='Текст')),
                ('articles_avtor', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('pug_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментрии',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Текст комент')),
                ('Articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Articles')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментрии',
            },
        ),
    ]
