# Generated by Django 2.2.4 on 2020-02-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_temp_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_articles',
            name='pub_date',
        ),
    ]
