# Generated by Django 2.2.4 on 2020-02-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_temp_articles_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Temp_Articles',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
