# Generated by Django 2.2.4 on 2020-02-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20200204_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Articles',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='User_acaunt',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Temp_Articles',
        ),
        migrations.DeleteModel(
            name='User_acaunt',
        ),
    ]
