# Generated by Django 2.2.4 on 2020-02-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20200204_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='articeles_title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='user_acaunt',
            name='admin',
            field=models.BooleanField(blank=True, verbose_name='Аминка'),
        ),
    ]
