# Generated by Django 3.0.7 on 2020-06-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_class', models.CharField(max_length=100, unique=True, verbose_name='Класификация продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100, verbose_name='Названя продукта')),
                ('shop', models.CharField(max_length=100, unique=True, verbose_name='Цена')),
                ('opsanie', models.TextField(verbose_name='Характкристика')),
                ('pub_date', models.DateTimeField(verbose_name='Дата выхода продажи')),
                ('ClassProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magges.ClassProduct')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
