# Generated by Django 2.2.4 on 2019-11-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artical_title', models.CharField(max_length=200, verbose_name='Названия стати')),
                ('artical_text', models.TextField(verbose_name='Текст стати')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Текст комент')),
                ('Hello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hello.Hello')),
            ],
        ),
    ]
