# Generated by Django 2.2.4 on 2020-01-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='User name')),
                ('user_password', models.CharField(max_length=50, verbose_name='User password')),
                ('email', models.CharField(max_length=20, verbose_name='Email')),
                ('sekret', models.TextField(verbose_name='Секрктный вопрос')),
                ('number_phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('create_date', models.DateTimeField(verbose_name='Дата регестрации')),
            ],
        ),
    ]
